### ISSUE TITLE
Parser throws error when accessing array with dot/bracket notation

### ISSUE THREAD

**Issue by jcardali** [handlebars-lang/handlebars.js#1717]
Fiddle works : https://jsfiddle.net/w59oLkgz/11/

But with something similar, I get the following stack trace:
```
(node:37082) UnhandledPromiseRejectionWarning: Error: Parse error on line 256:
...{productReasonsPair.0}}                
-----------------------^
Expecting 'ID', got 'NUMBER'
    at Parser.parseError (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Parser.parse (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at HandlebarsEnvironment.parseWithoutProcessing (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at preprocess (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/parser/tokenizer-event-handlers.js:333:22)
    at new ParseResult (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/ember-template-recast/src/parse-result.js:90:15)
    at Object.parse (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/ember-template-recast/src/index.js:8:16)
    at Prettier.exit (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/ember-template-lint-plugin-prettier/lib/rules/prettier.js:103:34)
    at /Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/ember-template-lint/lib/rules/base.js:297:21
    at visitNode (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/traversal/traverse.js:111:16)
    at traverse (/Users/jcardali/Documents/GitHub/mortgage/mortgage/frontend/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/traversal/traverse.js:219:3)
```

**Comment by runspired** [comment]
I get this as well when using ember-template-lint

**Comment by jaylinski** [comment]
> But with something similar

Can be more specific?

**Comment by nknapp** [comment]
In your fiddle, the `0` is wrapped in brackets `.[0]`. That is the correct syntax. The error messag suggests that you used

```hbs
{{productReasonsPair.0}}
```

but it should be

```hbs
{productReasonsPair.[0]}}
```

**Comment by runspired** [comment]
@nknapp I think you've misunderstood the issue. Specifically the bracket syntax errors, the message suggests there are no brackets, but there are.
