### ISSUE TITLE
dynamic partials cause (lookupProperty(...) || (depth0 && lookupProperty(...)) || alias3).call is not a function

### ISSUE THREAD

**Issue by leonardlin** [handlebars-lang/handlebars.js#1727]
Before filing issues, please check the following points first:

Used versions:
handlesbars: 4.7.6

partials is saved in:
/views/partials/filename.handlesbars
varPartial = 'filename';

main template uses
{{> (varPartial)}}

outcome:

TypeError: (lookupProperty(...) || (depth0 && lookupProperty(...)) || alias3).call is not a function
at Object.eval [as main] (eval at createFunctionContext (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), :11:148)
at main (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
at ret (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
at ret (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
at ExpressHandlebars._renderTemplate (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:253:10)
at ExpressHandlebars.render (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:166:21)
at async ExpressHandlebars.renderView (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:224:15)

If I use
{{> 'filename'}}

It works

reproduced on fiddle: 
Works with fix partial-name: https://jsfiddle.net/t9p508or/

Error with dynamic partial-name: https://jsfiddle.net/t9p508or/1/

**Comment by knownasilya** [comment]
Getting this same error when express-handlebars passes a template to compile to hbs, although I'm not using any partials at all.

**Comment by knownasilya** [comment]
Ah looks like the helper was defined in a .ts file, but `required` so the .default wasn't used.

**Comment by beshur** [comment]
So is there a resolution for this one?

**Comment by jaylinski** [comment]
You can use the `lookup`-helper, as described in the docs:

```
var template = Handlebars.compile("{{name}} ({{age}} years old) {{> (lookup . 'partialName')}}");
var partial = Handlebars.compile('and has lastname {{lastname}}');

Handlebars.registerPartial('lastpartial', partial);

document.getElementById('output').innerHTML = template({name: 'Max', age: 38, partialName: 'lastpartial', lastname: 'Lee'});
```

**Comment by solomon-web** [comment]
I had this persisting for a long time , I figured out it was occurring because I passed a boolean variable into the "if" helper enclosed in a bracket [ {{#if  (<booleanVariable>)}} ], apparently it is not supposed to be passed in that manner. It is supposed to be passed like this [ {{#if  <booleanVariable>}} ]
