### ISSUE TITLE
The partial litreal could not be found

### ISSUE THREAD

**Issue by hurabafzal** [handlebars-lang/handlebars.js#1744]
at Object.invokePartial (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\runtime.js:332:11)
    at Object.invokePartialWrapper [as invokePartial] (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:11:28)
    at main (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\runtime.js:208:32)
    at ret (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\runtime.js:212:12)
    at ret (D:\webs\technicalmongo\anothertry\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:519:21)
    at D:\webs\technicalmongo\anothertry\node_modules\hbs\lib\hbs.js:84:19
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

i am constantly getting this error while trying to use partials

**Comment by hurabafzal** [comment]
<body>
    {{>party}}
    <section>
    <div id="home">
        <h1 class="h-primary">Welcome to my GameZone</h1>
        <p>Lorem ipsubusdam. Sapiente quidem pariatur consectetur beatae ex nesciunt sequi odit Lorem ipsum dolor sit, am Lenim! Consequatur cumque ratione expedita architecto! </p>
         <button class="btn">Join Us</button>
        
    </div>
    </section>

this is where i am using the partial

**Comment by jaylinski** [comment]
Please provide a reduced test-case: https://jsfiddle.net/4nbwjaqz/4/

**Comment by jaylinski** [comment]
Closing because of inactivity.
