### ISSUE TITLE
Correct Syntax Throwing Error for non empty value in context

### ISSUE THREAD

**Issue by satyajitnayk** [handlebars-lang/handlebars.js#2034]
**Syntax** 
```hbs
{{#if (name)}}{{/if}}
```

**Throw Error When pass non empty string for name in context**

| Empty value for name in context  | Non Empty value for name in context |
|----| --- |
| <img width="908" alt="image" src="https://github.com/handlebars-lang/handlebars.js/assets/32722867/ee171d74-21ff-4ed8-b416-56f048cf0b95"> | <img width="1459" alt="image" src="https://github.com/handlebars-lang/handlebars.js/assets/32722867/a07cd965-9acb-4d04-9a4e-9c01df73d0a8"> |

**Error String**

```cmd
   (lookupProperty(...) || (depth0 && lookupProperty(...)) || container.hooks.helperMissing).call is not a function
    

    Error: (lookupProperty(...) || (depth0 && lookupProperty(...)) || container.hooks.helperMissing).call is not a function
    at t._callbacks.<computed> (https://handlebarsjs.com/assets/js/8.214167ea.js:1:61688)
    at n (https://handlebarsjs.com/assets/js/8.214167ea.js:1:61432)
    at Worker.<anonymous> (https://handlebarsjs.com/assets/js/8.214167ea.js:1:61536)
```

**Comment by tiholic** [comment]
I too faced the same issue

**Comment by satyajitnayk** [comment]
Same is observed in other helpers too . This should be addressed as soon as possible as it could cause severe issue for whoever is using `handlebars` in production. Thoughts @jaylinski ?🤔


For example `lookup` helper

Same Error when there is non empty string in merge key:
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/c7777fb4-acd6-46aa-a05a-7146e131c2b7">

No Error when merge context key is empty string:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/549f77b8-756b-42a1-9711-f75af231187f">

**Comment by mohd-akram** [comment]
Do not wrap `name` in `()`. Parentheses are for sub-expressions. See the [documentation](https://handlebarsjs.com/guide/builtin-helpers.html).
